---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - image: lscr.io/linuxserver/plex:1.31.2.6810-a607d384f-ls157
          livenessProbe: &ref_0
            httpGet:
              path: /web/index.html
              port: 32400
          name: plex
          ports:
            - containerPort: 32400
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 2
          startupProbe: *ref_0
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /media
              name: plex-media
            - mountPath: /transcodes
              name: plex-transcodes
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-media
          nfs:
            path: /volume1/plex
            readOnly: false
            server: nas.home.bcbrookman.com
        - emptyDir:
            medium: Memory
          name: plex-transcodes
