---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: &app plex
  name: *app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  selector:
    app: *app
