---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - ../../base/cnpg/
patches:
  - target:
      kind: HelmRelease
      name: cnpg
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: "0.26.0"
