---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pihole
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: DNS1
              value: 192.168.20.1
            - name: DNSMASQ_LISTENING
              value: all
          image: pihole/pihole:latest
          name: pihole
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
      dnsConfig:
        options:
          - name: ndots
            value: '1'
