---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - pihole
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      containers:
        - image: pihole/pihole:latest
          name: pihole
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: 'DNS1'
              value: '192.168.20.1'
            - name: 'DNSMASQ_LISTENING'
              value: "all"
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
            - containerPort: 80
            - containerPort: 443
