---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  labels:
    app: pihole
  namespace: staging
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  creationTimestamp: null
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dnstcp
      port: 53
      targetPort: 53
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: pihole
