---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole
  name: pihole-tcp
spec:
  externalTrafficPolicy: Local
  ports:
    - name: dnstcp
      port: 53
      targetPort: 53
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: pihole
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole
  name: pihole-udp
spec:
  externalTrafficPolicy: Local
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
