---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homeops-actions-runner
spec:
  template:
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: '1'
        searches:
          - home.bcbrookman.com
      repository: bcbrookman/homeops

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: homeops-actions-runner-autoscaler
spec:
  maxReplicas: 5
  metrics:
    - scaleDownFactor: '0.5'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleUpThreshold: '0.75'
      type: PercentageRunnersBusy
  minReplicas: 1
  scaleTargetRef:
    kind: RunnerDeployment
    name: homeops-actions-runner
