# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bcbrookman
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: pip
    directory: /.requirements/
    schedule:
      interval: weekly
    assignees:
      - bcbrookman
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: terraform
    directory: /infrastructure-layer/terraform/
    schedule:
      interval: weekly
    assignees:
      - bcbrookman
    commit-message:
      prefix: chore
      include: scope
