---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
spec:
  template:
    spec:
      containers:
        - name: unifi
          image: ghcr.io/linuxserver/unifi-controller:7.3.76
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp
spec:
  loadBalancerIP: "192.168.20.214"
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
spec:
  loadBalancerIP: "192.168.20.214"
