# Ansible requirements file
---
roles:
  - name: geerlingguy.firewall
  - name: geerlingguy.security
  - name: geerlingguy.ntp
  - name: sbaerlocher.snmp
    version: 1.8.0

collections:
  - name: community.sops
