---
version: '3'

includes:
  reqs:
    taskfile: ./.requirements/tasks.yaml
    dir: ./.requirements/
    internal: true
  docs:
    taskfile: ./docs/tasks.yaml
    dir: ./docs/
  infrastructure-layer:
    aliases: [ifl]
    taskfile: ./infrastructure-layer/tasks.yaml
    dir: ./infrastructure-layer/
  platform-layer:
    aliases: [pfl]
    taskfile: ./platform-layer/tasks.yaml
    dir: ./platform-layer/
  software-layer:
    aliases: [swl]
    taskfile: ./software-layer/tasks.yaml
    dir: ./software-layer/

run: once

env:
  ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections/
  ANSIBLE_ROLES_PATH: ~/.ansible/roles/
  TF_WORKSPACE: none
  TF_IN_AUTOMATION: true
  YAMLLINT_CONFIG_FILE: '{{.ROOT_DIR}}/.yamllint'

tasks:
  default:
    cmds: [task --list]
    silent: true

  all:lint:
    aliases: [lint]
    desc: Lint all the things
    cmds:
      - task: root:lint
      - task: infrastructure-layer:lint
      - task: platform-layer:lint
      - task: software-layer:lint
      - task: docs:lint

  all:deploy:
    aliases: [deploy]
    desc: Deploy all the things
    cmds:
      - task: infrastructure-layer:deploy
      - task: platform-layer:deploy
      - task: software-layer:deploy
      - task: docs:deploy

  docker-test:start:
    desc: Start container for CI/CD testing
    cmds:
      - task: docker-test:pull
      - task: docker-test:run
      - task: docker-test:setup
    status:
      - docker ps | grep homelab-cicd

  docker-test:setup:
    desc: Run setup tasks inside CI/CD test container
    deps:
      - docker-test:start
    cmds:
      - task: docker-test:setup-python
      - task: docker-test:setup-task
      - task: docker-test:setup-terraform
      - task: docker-test:start-dind

  docker-test:kill:
    desc: Kill CI/CD test container
    cmds:
      - docker rm --force homelab-cicd

  docker-test:exec:
    desc: Exec into CI/CD test container
    deps:
      - docker-test:start
    cmds:
      - docker exec -it homelab-cicd sudo bash

  docker-test:pull: docker pull summerwind/actions-runner:latest

  docker-test:run: docker run -d --name homelab-cicd
                   -v ./:/homelab -w /homelab --privileged
                   summerwind/actions-runner-dind:latest 'sleep infinity'

  docker-test:apt-update: docker exec homelab-cicd sudo apt update

  docker-test:setup-python:
    cmds:
      - task: docker-test:apt-update
      - docker exec homelab-cicd sudo apt install -y python3.9
      - docker exec homelab-cicd sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
    status:
      - docker exec homelab-cicd python3 --version | grep 3.9

  docker-test:setup-task:
    cmds:
      - docker exec homelab-cicd
        sudo sh -c "$(curl -L https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin/
    status:
      - docker exec homelab-cicd task --version

  docker-test:setup-terraform:
    cmds:
      - docker exec homelab-cicd
        sudo curl -L https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_linux_amd64.zip
        --output /tmp/terraform.zip
      - docker exec homelab-cicd sudo unzip -o /tmp/terraform.zip -d /tmp/terraform/
      - docker exec homelab-cicd sudo mv /tmp/terraform/terraform /usr/local/bin/
    status:
      - docker exec homelab-cicd terraform -version | grep v1.4.4

  docker-test:start-dind:
    cmds:
      - docker exec homelab-cicd sudo dockerd &
    status:
      - pgrep -f dockerd

  root:lint:
    desc: Lint files in the project root
    deps:
      - reqs:yamllint
    cmds:
      - yamllint *.y?ml .github/ .requirements/
