---
version: '3'

env:
  ANSIBLE_ROLES_PATH: ~/.ansible/roles/
  ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections/
  YAMLLINT_CONFIG_FILE: '{{.TASKFILE_DIR}}/.yamllint'

run: once

tasks:
  default:
    cmds: [task --list]
    silent: true

  all:setup:
    aliases: [setup]
    desc: Install/upgrade all dependencies
    cmds:
      - task: common:setup
      - task: docs:setup
      - task: infrastructure-layer:setup
      - task: platform-layer:setup
      - task: software-layer:setup

  all:lint:
    aliases: [lint]
    desc: Lint all files
    cmds:
      - task: common:lint
      - task: infrastructure-layer:lint
      - task: platform-layer:lint
      - task: software-layer:lint

  common:pip-depends: pip3 install --no-input --upgrade pip wheel

  common:ansible-depends:
    deps: [common:pip-depends]
    cmds:
      - pip3 install --no-input --upgrade ansible ansible-lint
      - ansible-galaxy install --force --role-file requirements.yaml

  common:general-depends:
    desc: Install/upgrade general dependencies common to all layers
    aliases: [common:setup]
    deps: [common:pip-depends]
    cmds: [pip3 install --no-input --upgrade --requirement requirements.txt]

  docs:setup:
    desc: Install/upgrade documentation dependencies
    dir: docs/
    deps: [common:pip-depends]
    cmds: [pip3 install --no-input --upgrade --requirement requirements.txt]

  common:lint:
    desc: Lint files common to all layers
    cmds: [yamllint .]

  infrastructure-layer:setup:
    desc: Install/upgrade infrastructure-layer dependencies
    dir: infrastructure-layer/
    deps:
      - common:general-depends
      - common:ansible-depends
    cmds:
      - ansible-galaxy install --force --role-file ansible/requirements.yaml

  infrastructure-layer:lint:
    desc: Lint all infrastructure layer files
    dir: infrastructure-layer/
    cmds: [cd ansible && ansible-lint]

  platform-layer:setup:
    desc: Install/upgrade platform-layer dependencies
    dir: platform-layer/
    deps:
      - common:general-depends
      - common:ansible-depends

  platform-layer:lint:
    desc: Lint all platform-layer files
    dir: platform-layer/
    cmds: [cd ansible && ansible-lint]

  software-layer:setup:
    desc: Install/upgrade software-layer dependencies
    dir: software-layer/
    deps: [common:general-depends]
    cmds:
      - docker pull k8s.gcr.io/kustomize/kustomize:v4.5.7
      - docker pull ghcr.io/yannh/kubeconform:latest-alpine

  software-layer:lint:
    desc: Lint all software-layer files
    dir: software-layer/
    cmds:
      - cat k8s/clusters/staging/*.y*ml k8s/clusters/production/*.y*ml | $KUBECONFORM
      - $KUSTOMIZE build /k8s/infrastructure/staging | $KUBECONFORM
      - $KUSTOMIZE build /k8s/infrastructure/production | $KUBECONFORM
      - $KUSTOMIZE build /k8s/apps/staging | $KUBECONFORM
      - $KUSTOMIZE build /k8s/apps/production | $KUBECONFORM
    vars:
      WORKING_DIR:
        sh: pwd
    env:
      KUSTOMIZE: docker run --rm -v {{.WORKING_DIR}}/k8s:/k8s k8s.gcr.io/kustomize/kustomize:v4.5.7
      KUBECONFORM: >
        docker run -i --rm ghcr.io/yannh/kubeconform:latest-alpine
        -summary
        -schema-location default
        -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{`{{.Group}}`}}/{{`{{.ResourceKind}}`}}_{{`{{.ResourceAPIVersion}}`}}.json
