---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: homer
  name: homer-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
