---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./etherpad/
  - ./github-arc/
  - ./home-assistant/
  - ./homer/
  - ./kube-prometheus-stack/
  - ./mealie/
  - ./pi-hole/
  - ./plex/
  - ./tautulli/
  - ./uptime-kuma/
  - ./unifi/
patches:
  - target:
      kind: ImageUpdateAutomation
    patch: |-
      - op: replace
        path: /spec/git/commit/messageTemplate
        value: >
          {{ if .Updated.Images -}}
          chore(swl): update {{ (index .Updated.Images 0).Repository }}
          to {{ (index .Updated.Images 0).Identifier }} (talos3203)
          {{ else -}}
          chore(swl): unspecified update
          by {{ .AutomationObject }} ImageUpdateAutomation (talos3203)
          {{ end -}}
