---
# Groups of hosts
k3s_vms:
  hosts:
    k3s-prod-vm[01:03]:
pgsql_cts:
  hosts:
    pgsql-ct01:

# Groups of groups
all_servers:
  children:
    k3s_vms:
    pgsql_cts:
master:
  children:
    k3s_vms:
node:
  children:
k3s_cluster:
  children:
    master:
    node:
