---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ../../base/longhorn/
  - ./recurringjobs.yaml
patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /apiVersion
        value: helm.toolkit.fluxcd.io/v2
  - target:
      kind: HelmRelease
      name: longhorn
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: "1.8.2"
