---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  path: ./software-layer/k8s/apps/talos3203
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-customresources
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: apps
  interval: 10m0s
  path: ./software-layer/k8s/apps/talos3203/customresources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
