---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etherpad
  name: etherpad
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9001
  selector:
    app: etherpad
  type: ClusterIP
