---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/mealie/resources/
  - ./ingresses.yaml
  - ./secrets.sops.yaml
patches:
  - path: ./configmaps.yaml
