# Deploy with 'docker stack deploy -c docker-compose.yml librenms'
---
version: "3.5"

services:
  db:
    image: mariadb:10.5
    command:
      - mysqld
      - --innodb-file-per-table=1
      - --lower-case-table-names=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - librenms_db_vol:/var/lib/mysql
    secrets:
      - source: librenms_db_rootpw.v1
        target: librenms_db_rootpw
      - source: librenms_db_user.v1
        target: librenms_db_user
      - source: librenms_db_pass.v1
        target: librenms_db_pass
    environment:
      MYSQL_DATABASE: librenms
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/librenms_db_rootpw
      MYSQL_USER_FILE: /run/secrets/librenms_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/librenms_db_pass

  memcached:
    image: memcached:1.6-alpine

  redis:
    image: redis:6.2-alpine

  msmtpd:
    image: crazymax/msmtpd:1.8.15
    secrets:
      - source: librenms_msmtpd_user.v1
        target: librenms_msmtpd_user
      - source: librenms_msmtpd_pass.v1
        target: librenms_msmtpd_pass
    env_file:
      - msmtpd.env
    environment:
      SMTP_USER_FILE: /run/secrets/librenms_msmtpd_user
      SMTP_PASSWORD_FILE: /run/secrets/librenms_msmtpd_pass

  app:
    image: librenms/librenms:21.4.0
    entrypoint: /librenms_entrypoint.sh /init
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8002
        protocol: tcp
    depends_on:
      - db
      - memcached
      - msmtpd
    volumes:
      - librenms_app_vol:/data
      - ./librenms_entrypoint.sh:/librenms_entrypoint.sh:ro
    env_file:
      - librenms.env
    secrets:
      - source: librenms_db_user.v1
        target: librenms_db_user
      - source: librenms_db_pass.v1
        target: librenms_db_pass
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_DATABASE: librenms
      DB_USER_FILE: /run/secrets/librenms_db_user
      DB_PASSWORD_FILE: /run/secrets/librenms_db_pass
      DB_HOST: db
      DB_TIMEOUT: 60

  dispatcher:
    image: librenms/librenms:21.4.0
    entrypoint: /librenms_entrypoint.sh /init
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    volumes:
      - librenms_app_vol:/data
      - ./librenms_entrypoint.sh:/librenms_entrypoint.sh:ro
    env_file:
      - librenms.env
    secrets:
      - source: librenms_db_user.v1
        target: librenms_db_user
      - source: librenms_db_pass.v1
        target: librenms_db_pass
    environment:
      PUID: 1000
      PGID: 1000
      DB_HOST: db
      DB_NAME: librenms
      DB_USER_FILE: /run/secrets/librenms_db_user
      DB_PASSWORD_FILE: /run/secrets/librenms_db_pass
      DB_TIMEOUT: 60
      DISPATCHER_NODE_ID: dispatcher1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      SIDECAR_DISPATCHER: 1

#  syslogng:
#    image: librenms/librenms:21.4.0
#    entrypoint: /librenms_entrypoint.sh /init
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
#    depends_on:
#      - app
#    ports:
#      - target: 514
#        published: 514
#        protocol: tcp
#      - target: 514
#        published: 514
#        protocol: udp
#    volumes:
#      - librenms_app_vol:/data
#      - ./librenms_entrypoint.sh:/librenms_entrypoint.sh:ro
#    env_file:
#      - librenms.env
#    secrets:
#      - source: librenms_db_user.v1
#        target: librenms_db_user
#      - source: librenms_db_pass.v1
#        target: librenms_db_pass
#    environment:
#      PUID: 1000
#      PGID: 1000
#      DB_HOST: db
#      DB_NAME: librenms
#      DB_USER_FILE: /run/secrets/librenms_db_user
#      DB_PASSWORD_FILE: /run/secrets/librenms_db_pass
#      DB_TIMEOUT: 60
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_DB: 0
#      SIDECAR_SYSLOGNG: 1

volumes:
  librenms_db_vol:
    external: true
  librenms_app_vol:
    external: true

secrets:
  librenms_db_rootpw.v1:
    external: true
  librenms_db_user.v1:
    external: true
  librenms_db_pass.v1:
    external: true
  librenms_msmtpd_user.v1:
    external: true
  librenms_msmtpd_pass.v1:
    external: true
