---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources/
  - ./cnpg/
  - ./longhorn/
  - ./metallb/
  - ./namespaces.yaml
patches:
  - target:
      kind: HelmRepository
    patch: |-
      - op: replace
        path: /apiVersion
        value: source.toolkit.fluxcd.io/v1
