---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: home-assistant
spec:
  image: lscr.io/linuxserver/homeassistant
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: home-assistant
spec:
  imageRepositoryRef:
    name: home-assistant
  policy:
    semver:
      range: '>=1.0.0 <1000.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: home-assistant
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{ if .Updated.Images -}}
          Bump {{ (index .Updated.Images 0).Repository }} to {{ (index .Updated.Images 0).Identifier }}
        {{ else -}}
          Unspecified change by {{ .AutomationObject }} ImageUpdateAutomation
        {{ end -}}
    push:
      branch: fluxcdbot/updates/home-assistant
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: software-layer/k8s/apps/base/home-assistant/
    strategy: Setters
