---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: home-assistant
spec:
  image: lscr.io/linuxserver/homeassistant
  interval: 4h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: home-assistant
spec:
  imageRepositoryRef:
    name: home-assistant
  filterTags:
    extract: $YYYY.$MM.$RELEASE
    pattern: ^(?P<YYYY>\d{4})\.(?P<MM>\d{1,2})\.(?P<RELEASE>\d+)$
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: home-assistant
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{ if .Updated.Images -}}
          Bump {{ (index .Updated.Images 0).Repository }} to {{ (index .Updated.Images 0).Identifier }}
        {{ else -}}
          Unspecified change by {{ .AutomationObject }} ImageUpdateAutomation
        {{ end -}}
    push:
      branch: fluxcdbot/updates/home-assistant
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: software-layer/k8s/apps/base/home-assistant/
    strategy: Setters
