---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unifi
    env: prod
  name: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
      env: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi
        env: prod
    spec:
      containers:
        - env:
            - name: TZ
              value: UTC
          image: ghcr.io/linuxserver/unifi-controller:latest
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: unifi
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 3478
              protocol: UDP
            - containerPort: 8843
            - containerPort: 8880
            - containerPort: 6789
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 2048Mi
            requests:
              cpu: 200m
          volumeMounts:
            - mountPath: /config
              name: unifi-data
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-data
