---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
  name: unifi-tcp
spec:
  ports:
    - name: web-interface
      port: 8443
      targetPort: 8443
    - name: device-control
      port: 8080
      targetPort: 8080
    - name: https-guest-portal
      port: 8843
      targetPort: 8843
    - name: http-guest-portal
      port: 8880
      targetPort: 8880
    - name: speed-test
      port: 6789
      targetPort: 6789
  selector:
    app: unifi
    env: prod
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
  name: unifi-udp
spec:
  ports:
    - name: stun-service
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: device-discovery
      port: 10001
      protocol: UDP
      targetPort: 10001
    - name: device-l2-discovery
      port: 1900
      protocol: UDP
      targetPort: 1900
    - name: remote-syslog
      port: 5514
      protocol: UDP
      targetPort: 5514
  selector:
    app: unifi
  type: LoadBalancer
