# unifi.service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
spec:
  type: LoadBalancer
  ports:
    - name: web-interface
      port: 8443
      targetPort: 8443
    - name: device-control
      port: 8080
      targetPort: 8080
    - name: https-guest-portal
      port: 8843
      targetPort: 8843
    - name: http-guest-portal
      port: 8880
      targetPort: 8880
    - name: speed-test
      port: 6789
      targetPort: 6789
  selector:
    app: unifi
    env: prod
