# unifi.deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  labels:
    app: unifi
    env: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi
      env: prod
  template:
    metadata:
      labels:
        app: unifi
        env: prod
    spec:
      containers:
        - name: unifi
          image: ghcr.io/linuxserver/unifi-controller:latest
          resources:
            requests:
              cpu: 200m
            limits:
              memory: 2048Mi
          env:
            - name: TZ
              value: UTC
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 3478
              protocol: UDP
            - containerPort: 8843
            - containerPort: 8880
            - containerPort: 6789
          volumeMounts:
            - name: unifi-data
              mountPath: /config
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-data
      dnsConfig:
        options:
          - name: ndots
            value: "1"
