---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: home-assistant
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
