---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    service:
      spec:
        loadBalancerIP: "192.168.20.210"
        externalTrafficPolicy: Local
