---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name kube-prometheus-stack
spec:
  releaseName: *name
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "44"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 60m
