---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: uptime-kuma
spec:
  image: louislam/uptime-kuma
  interval: 4h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: uptime-kuma
spec:
  filterTags:
    pattern: ^\d+\.\d+\.\d+-alpine$
  imageRepositoryRef:
    name: uptime-kuma
  policy:
    semver:
      range: '>=1.0.0-x <1000.0.0-x'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: uptime-kuma
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{ if .Updated.Images -}}
          Bump {{ (index .Updated.Images 0).Repository }} to {{ (index .Updated.Images 0).Identifier }}
        {{ else -}}
          Unspecified change by {{ .AutomationObject }} ImageUpdateAutomation
        {{ end -}}
    push:
      branch: fluxcdbot/updates/uptime-kuma
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: software-layer/k8s/apps/base/uptime-kuma/
    strategy: Setters
