---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-hole
resources:
  - ../../../base/pi-hole/resources/
patches:
  - path: ./svc-tcp-patch.yaml
  - path: ./svc-udp-patch.yaml
images:
  - name: pihole/pihole
    newTag: 2025.06.2 # {"$imagepolicy": "flux-system:pi-hole:tag"}
