---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          image: louislam/uptime-kuma:latest
          name: uptime-kuma
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-data
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      restartPolicy: Always
      volumes:
        - name: uptime-kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
