---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
