---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web-ui
      port: 3001
      targetPort: 3001
  selector:
    app: uptime-kuma
