kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-databases
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  fsType: "ext4"
  dataLocality: "strict-local"
  recurringJobSelector: '[
      {
        "name":"longhorn-cnpg",
        "isGroup":true
      }
    ]'
