apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wizarr
  name: wizarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wizarr
    spec:
      containers:
        - env:
            - name: APP_URL
              value: https://wizarr.bcbrookman.com
            - name: TZ
              value: UTC
          image: ghcr.io/wizarrrr/wizarr:2.2.0 # {"$imagepolicy": "flux-system:wizarr"}
          name: wizarr
          ports:
            - containerPort: 5690
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - mountPath: /data/database
              name: wizarr-database
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: wizarr-database
          persistentVolumeClaim:
            claimName: wizarr-database
