---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wizarr
  name: wizarr-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
