---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wizarr
  name: wizarr
spec:
  ports:
    - name: http
      port: 5690
      targetPort: 5690
  selector:
    app: wizarr
  type: ClusterIP
