---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name daily-backup
spec:
  concurrency: 1
  cron: 0 3 * * SUN,MON,TUE,WED,THU,FRI
  groups:
    - default
  labels: {}
  name: *name
  retain: 2
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: &name weekly-backup
spec:
  concurrency: 1
  cron: 0 3 * * SAT
  groups:
    - default
  labels: {}
  name: *name
  retain: 2
  task: backup
