---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pi-hole
  labels:
    app: pi-hole
  name: pi-hole-tcp
spec:
  externalTrafficPolicy: Local
  ports:
    - name: dnstcp
      port: 53
      targetPort: 5353
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: pi-hole
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pi-hole
  labels:
    app: pi-hole
  name: pi-hole-udp
spec:
  externalTrafficPolicy: Local
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 5353
  selector:
    app: pi-hole
  type: LoadBalancer
