---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./software-layer/k8s/infrastructure/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
