---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: unifi
spec:
  image: lscr.io/linuxserver/unifi-controller
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: unifi
spec:
  imageRepositoryRef:
    name: unifi
  policy:
    semver:
      range: '>=1.0.0 <1000.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: unifi
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: Bump {{ (index .Updated.Images 0).Repository }} to {{ (index .Updated.Images 0).Identifier }}
    push:
      branch: fluxcdbot/updates/unifi
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: software-layer/k8s/apps/base/unifi/
    strategy: Setters
