---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: unifi
spec:
  image: lscr.io/linuxserver/unifi-controller
  interval: 4h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: unifi
spec:
  imageRepositoryRef:
    name: unifi
  policy:
    semver:
      range: '>=1.0.0 <1000.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: unifi
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{ if .Updated.Images -}}
          Bump {{ (index .Updated.Images 0).Repository }} to {{ (index .Updated.Images 0).Identifier }}
        {{ else -}}
          Unspecified change by {{ .AutomationObject }} ImageUpdateAutomation
        {{ end -}}
    push:
      branch: fluxcdbot/updates/unifi
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: software-layer/k8s/apps/base/unifi/
    strategy: Setters
