apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - env:
            - name: PUID
              value: '1001'
            - name: PGID
              value: '1001'
            - name: TZ
              value: UTC
          image: lscr.io/linuxserver/plex:1.32.8 # {"$imagepolicy": "flux-system:plex"}
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: plex
          ports:
            - containerPort: 32400
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /identity
              port: 32400
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: '2'
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /media
              name: plex-media
            - mountPath: /transcodes
              name: plex-transcodes
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-media
          nfs:
            path: /volume1/plex
            readOnly: false
            server: nas.home.bcbrookman.com
        - emptyDir:
            medium: Memory
          name: plex-transcodes
