version: "3.6"

services:
  app:
    image: splunk/splunk:8.1
    entrypoint: ["/splunk_entrypoint.sh", "/sbin/entrypoint.sh"]
    command: start-service
    volumes:
       - splunk-var:/opt/splunk/var
       - splunk-etc:/opt/splunk/etc
       - ./splunk_entrypoint.sh:/splunk_entrypoint.sh:ro
    networks:
      - host_net
    secrets:
      - source: splunk_app_pass.v1
        target: splunk_app_pass
    environment:
      SPLUNK_LICENSE_URI: Free
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD_FILE: /run/secrets/splunk_app_pass

networks:
  host_net:
    external: true
    name: "host"

volumes:
  splunk-var:
    external: true
  splunk-etc:
    external: true

secrets:
  splunk_app_pass.v1:
    external: true
