apiVersion: v1
kind: Service
metadata:
  name: buoy-svc
  labels:
    app: buoy
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: buoy
