---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buoy
  name: buoy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: buoy
  template:
    metadata:
      labels:
        app: buoy
    spec:
      restartPolicy: Always
      containers:
        - image: bcbrookman/buoy:latest
          name: buoy
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5000
