---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tautulli
  name: tautulli-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
