---
# Groups of hosts
k3s_vms:
  hosts:
    k3s-staging-vm[01:05]:

# Groups of groups
all_servers:
  children:
    k3s_vms:
master:
  children:
    k3s_vms:
node:
  children:
k3s_cluster:
  children:
    master:
    node:
