---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
spec:
  template:
    spec:
      containers:
        - name: tautulli
          image: lscr.io/linuxserver/tautulli:latest
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
spec:
  loadBalancerIP: "192.168.20.218"
