---
- name: Prepare servers for K3s
  hosts: k3s_cluster
  become: true

  tasks:
    - name: Install prerequisite packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - curl
          - open-iscsi
          - nfs-common
        state: present

    - name: Install open-iscsi (for Longhorn)
      ansible.builtin.apt:
        update_cache: true
        package: open-iscsi
        state: present

    - name: Set alternative for iptables as iptables-legacy
      community.general.alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy

    - name: Set alternative for ip6tables as ip6tables-legacy
      community.general.alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy

    - name: Turn off swap on Debian nodes
      ansible.builtin.shell: set -o pipefail && cat /proc/swaps | grep -v Filename && swapoff --all
      args:
        executable: /bin/bash
      register: deb_swapoff
      changed_when: deb_swapoff.rc == 0
      failed_when: deb_swapoff.rc > 1
      when: ansible_distribution == "Debian"

    - name: Disable swap mounts in fstab on Debian nodes
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s+sw\s+.*)$'
        replace: '# \1'
      when: ansible_distribution == "Debian"

    - name: Turn off swap on Raspbian nodes
      ansible.builtin.shell: set -o pipefail && cat /proc/swaps | grep -v Filename && dphys-swapfile swapoff && dphys-swapfile uninstall
      args:
        executable: /bin/bash
      register: rpi_swapoff
      changed_when: rpi_swapoff.rc == 0
      failed_when: rpi_swapoff.rc > 1
      when: ansible_distribution == "Raspbian"

    - name: Disable the dphys-swapfile service on Raspbian nodes
      ansible.builtin.service:
        name: dphys-swapfile.service
        state: stopped
        enabled: false
      when: ansible_distribution == "Raspbian"
