apiVersion: v1
kind: Service
metadata:
  name: buoy-service
  labels:
    app: buoy
  namespace: staging
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: buoy
  loadBalancerIP: "192.168.20.203"
