---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pi-hole
spec:
  image: pihole/pihole
  interval: 4h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pi-hole
spec:
  filterTags:
    extract: $YYYY.$MM.$RELEASE
    pattern: ^(?P<YYYY>\d{4})\.(?P<MM>\d{2})\.(?P<RELEASE>\d+)$
  imageRepositoryRef:
    name: pi-hole
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: pi-hole
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{ if .Updated.Images -}}
          Bump {{ (index .Updated.Images 0).Repository }} to {{ (index .Updated.Images 0).Identifier }}
        {{ else -}}
          Unspecified change by {{ .AutomationObject }} ImageUpdateAutomation
        {{ end -}}
    push:
      branch: fluxcdbot/updates/pi-hole
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: software-layer/k8s/apps/base/pi-hole/
    strategy: Setters
