---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  image: pihole/pihole
  interval: 1h0m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  filterTags:
    extract: $YYYY.$MM.$RELEASE
    pattern: ^(?P<YYYY>\d{4})\.(?P<MM>\d{2})\.(?P<RELEASE>\d+)$
  imageRepositoryRef:
    name: pi-hole
  policy:
    alphabetical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: fluxcdbot/updates/pi-hole
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: apps/base/pi-hole/
    strategy: Setters
