apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  labels:
    app: pihole
  namespace: default
spec:
  loadBalancerIP: "192.168.20.213"
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  labels:
    app: pihole
  namespace: default
spec:
  loadBalancerIP: "192.168.20.213"
