---
# Groups of hosts
k3s_vms:
  hosts:
    k3s-prod-vm[01:05]:
other_servers:
  hosts:
    plex01:
    docker01:

# Groups of groups
all_servers:
  children:
    k3s_vms:
    other_servers:
master:
  children:
    k3s_vms:
node:
  children:
k3s_cluster:
  children:
    master:
    node:
