---
# Groups of hosts
pfsense_firewalls:
  hosts:
    pfsense[01:02]:
proxmox_servers:
  hosts:
    pve[01:03]:
unifi_aps:
  hosts:
    ubnt-ap[01:02]:
unifi_switches:
  hosts:
    ubnt-sw[01:03]:

# Groups of groups
all_servers:
  children:
    proxmox_servers:
unifi_gear:
  children:
    unifi_switches:
    unifi_aps:
