# server_base.yaml
---
- name: Apply base server configurations
  hosts: all_servers
  become: true

  handlers:
    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.security
    - sbaerlocher.snmp
    - bcbrookman.duplicati

  tasks:
    - name: Make sure QEMU Guest Agent is installed, if needed
      ansible.builtin.apt:
        update_cache: true
        package: qemu-guest-agent
        state: present
      when: ansible_system_vendor == "QEMU"

    - name: Make sure rsyslog and logrotate are installed
      ansible.builtin.apt:
        update_cache: true
        package:
          - rsyslog
          - logrotate
        state: present

    - name: Make sure rsyslog is configured
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: '*.* @@{{ syslog_dest_host }}:{{ syslog_dest_port }}'
        state: present
      notify: Restart rsyslog

    - name: Make sure rsyslog is enabled
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: true

    - name: Make sure logrotate timer is enabled
      ansible.builtin.service:
        name: logrotate.timer
        state: started
        enabled: true

    - name: Delete systemd-journald directory (if present)
      ansible.builtin.file:
        path: /var/log/journal
        state: absent
