---
apiVersion: v1
kind: Service
metadata:
  name: buoy-svc
  labels:
    app: buoy
  namespace: default
spec:
  loadBalancerIP: "192.168.20.232"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buoy
  name: buoy
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: bcbrookman/buoy:latest
          name: buoy
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5000
