apiserver_endpoint: 192.168.0.1
apiserver_port: 7443
extra_agent_args: null
extra_server_args: --disable servicelb --disable local-storage --tls-san 192.168.0.1
firewall_enabled_at_boot: false
firewall_state: stopped
k3s_token: ENC[AES256_GCM,data:vLoU9QncVO5B8JRuellfxDhFCE+0CMNnOKiFO2O1MmT0C3PiuQwVNninlMxXzqhX+Xk=,iv:bKNXWEWgWkamgTat5JZJuvDN6SsuYw6M43AT3taZKkg=,tag:LMqBlQshqAbrElTodVapew==,type:str]
k3s_version: v1.28.2+k3s1
systemd_dir: /etc/systemd/system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1azf8jz2rq6upyktxe0ntqnlnpwlsmuspgqy3ak3rh609vqk2recqdfznyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaW41VGVzSDNQKzRuKzhN
            ckxmd09ZSC8yb0d5M0VYWVdjMnIvUHdDTUc4ClBFMkJlZDBvSXQycVhadUdQVmNK
            RVlUbXJMbVd2S28vNFEvOHJFZk00MzAKLS0tIFBpT2JKeW53aG1VUHdpUzVqNWpq
            ZmNvNnpCWStWMHZiT3U2YU5Rdit4MnMKuNDIxtJauDyolg9JZewcmZ0BLBK638dP
            yCBtUBdWkhVSqTZRVD9eN6rkbaffAC5zsb+41q9DPqk2zPhmygAj+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T16:14:28Z"
    mac: ENC[AES256_GCM,data:LmMmAnNh6rNasLPU1EtHe53nze1XpJAR05NYzTkMMTYgQy309q9Yrero1PL5Zn6wY+GZ6sYQYgIWiApwaWf2BgdA3C+W3qwNWrg+ljO/9kPWUjPqn590O0lTb99rxq1MBopXrUXCSbEpdHmoIG14rkjLiIWJK4lAbyFNaNaEz80=,iv:CsoTD04x6QgFTR5IIxxXm9c6eH8KMUZ3UQm6kpYEaLs=,tag:1eqkgeXkmgK7ojbmcUFuFQ==,type:str]
    pgp: []
    encrypted_regex: (?i)user|pass|secret|key|token|^data$|^stringData$
    version: 3.7.3
