apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mealie
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mealie
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mealie
                topologyKey: kubernetes.io/hostname
      containers:
        - name: mealie
          env:
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  key: host
                  name: mealie-db-app
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: mealie-db-app
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: mealie-db-app
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mealie-db-app
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mealie-db-app
          envFrom:
            - configMapRef:
                name: mealie
          image: ghcr.io/mealie-recipes/mealie:latest
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/app/about
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 9000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/app/about
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: &memory 500Mi
            requests:
              cpu: 300m
              memory: *memory
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - mountPath: /app/data/
              name: mealie-data
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
