---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: mealie
  type: ClusterIP
