---
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v3

      - name: Setup the environment
        run: ./run.sh -e setup

      - name: Run linters
        run: ./run.sh -e lint
