---
name: Common CI

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v3

      - name: Setup the environment
        run: docker-compose build

      - name: Run linters
        run: docker-compose run task root:lint
