---
name: Dependabot PR Auto-Merge

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      startsWith(github.event.pull_request.head.ref, 'dependabot/')
    runs-on: ubuntu-latest

    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"

      - name: Auto-merge PR
        run: gh pr merge --auto --squash "$PR_URL"
