---
name: Deploy Documentation

concurrency:
  group: docs
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  schedule:
    - cron: "0 0 * * 0"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: '3.19.0'

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Build docs
        run: task docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: [self-hosted, linux]
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
