---
name: Flux Auto-PR

on:  # yamllint disable-line rule:truthy
  create:

permissions:
  pull-requests: write

jobs:
  Auto-PR:
    if: ${{ startsWith(github.ref_name, 'fluxcdbot/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo at current context
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create new Pull Request
        run: |
          gh pr create --base "main" --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
