---
name: Platform Layer CI

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/platform-layer*"
      - ".requirements/**"
      - "platform-layer/**"

jobs:
  lint:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v3

      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: '3.19.0'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.4'
          terraform_wrapper: false

      - name: Run linters
        run: task platform-layer:lint
