---
name: Software Layer CI

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/software-layer*"
      - ".requirements/**"
      - "software-layer/**"

jobs:
  lint:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: '3.19.0'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run linters
        run: task software-layer:lint
